# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:03
from __future__ import unicode_literals

import crop_override.field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(editable=False, max_length=200)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_dt', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=b'uploads/file/%Y-%m')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(editable=False, max_length=200)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_dt', models.DateTimeField(auto_now_add=True)),
                ('file', crop_override.field.OriginalImage(max_length=200, null=True, upload_to=b'uploads/photos/%Y-%m', verbose_name=b'Photo')),
                ('caption', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[(b'web', b'Web'), (b'twittpic', b'TwittPic'), (b'email', b'Email'), (b'misc', b'Miscelaneous')], default=b'web', max_length=16)),
                ('square_crop', crop_override.field.CropOverride(blank=True, help_text=b'Usages: Blog Photo, Tool Photo', max_length=200, null=True, upload_to=b'uploads/photos/%Y-%m', verbose_name=b'Square Crop (1:1)')),
                ('landscape_crop', crop_override.field.CropOverride(blank=True, help_text=b'Usages: Featured Blog Photo, Lab Photo', max_length=200, null=True, upload_to=b'uploads/photos/%Y-%m', verbose_name=b'Landscape Crop (3:2)')),
                ('portrait_crop', crop_override.field.CropOverride(blank=True, help_text=b'Usages: None', max_length=200, null=True, upload_to=b'uploads/photos/%Y-%m', verbose_name=b'Portrait Crop (2:3)')),
                ('external_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='TaggedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('order', models.IntegerField(default=9999)),
                ('private', models.BooleanField(default=False, help_text=b'Files will not appear until after the user has completed a class.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MiscFile')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('order', models.IntegerField(default=9999)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.PhotoTag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
